server {
    listen 80;
    server_name localhost;

    # Nơi đặt file gốc html mà Vite vừa build xong
    root /usr/share/nginx/html;
    index index.html;

    # Cấu trúc cốt lỗi hỗ trợ Vue Router hoạt động trong History Mode tĩnh
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Báo lỗi tùy chọn nếu có
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
